### ISSUE TITLE
All hosts show UP even when DOWN

### ISSUE THREAD

**Issue by Eddiiie** [vozlt/nginx-module-vts#105]
This module does SO much I must be missing something with health checks.
I have 10 servers configured, took 5 offline, still 10 say UP.

What is it that I am missing?

**Comment by hadret** [comment]
hi @Eddiiie,

wish there would be an answer from someone more knowledgable, but here's my observation that may be related to the one you have:

 * numbers for given servers in given upstream are updated in given interval in the web interface and it somewhat reflects the truth (i.e. if you balance out the upstream, the numbers for it become static regardless of the state);
 * state changes are updated only on the start, reload and restart, but **are not** handled dynamically on already running vts instance;

The only case where I can imagine state function to be useful in current implementation, is when you are balancing out the upstream servers by adjusting configuration on nginx level (i.e. adding down) and then reloading it. Otherwise, the state will not change unless you reload or restart nginx.

**Comment by Eddiiie** [comment]
Thank you for taking the time to comment and confirmation that there is not even a simple TCP handshake check.
Seems lacking to me.

**Comment by vozlt** [comment]
@oleg-jukovec 's [pull request](https://github.com/vozlt/nginx-module-vts/pull/112) is merged.
Thanks to @oleg-jukovec.

Basically, the `down`:(true|false) field in **upstreamZones** is just a mark the [ngx_http_upstream_module](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#server)(eg. `server backend3.example.com down`)'s server down, not actual upstream server state.
It will changed to actual state by [112 Patch](https://github.com/vozlt/nginx-module-vts/pull/112) if you enabled the upstream zone directive.
