### ISSUE TITLE
filter_by_set_key get error

### ISSUE THREAD

**Issue by tonychenl** [vozlt/nginx-module-vts#129]
nginx.conf 

....
vhost_traffic_status_zone shared:vhost_traffic_status:32m;
 server  {
.....
 vhost_traffic_status_filter_by_set_key $status  $host;
......

location /status {
                vhost_traffic_status_display;
                vhost_traffic_status_display_format html;
            }

}

http://ip:1010/status  -->>   get error page

error logs  "2018/06/21 09:34:46 [alert] 1#1: worker process 63 exited on signal 11 (core dumped)"

**Comment by vozlt** [comment]
Thanks for reporting.
I have some questions to confirm the problem because I can not reproduce the problem with the above settings.

1. What is the nginx-module-vts and nginx and os versions?
2. Please let me know `$ nginx -V` output information.
3. The best thing is backtrace information.
   * `$ ./configure --with-debug --with-cc-opt='-O0 -g' ...`
   * `$ sudo gdb <nginx_executable_path> <coredump_file_path>`
   * `$ sudo gdb /usr/sbin/nginx nginx.coredump.1981`
   * `(gdb) bt`

Please see the https://www.nginx.com/resources/admin-guide/debug/ for debugging.

**Comment by vozlt** [comment]
I fixed the suspicious part.
Please check if the error occurs again.
Thanks.

Latest commit: https://github.com/vozlt/nginx-module-vts/commit/7b1eb287db70ace635741fd212168b60071e7cd7

**Comment by Frodox** [comment]
Bump @tonychel
