### ISSUE TITLE
GeoIP.dat file format

### ISSUE THREAD

**Issue by PREngineer** [vozlt/nginx-module-vts#162]
https://support.maxmind.com/geolite-legacy-discontinuation-notice/

Apparently the GeoIP.dat file format of the database was changed and it will not be released like that ever.

In your examples of the nginx config, you use the GeoIP.dat file.

Is this necessary for it to recognize the countries properly?

Can it be updated to use the new format?

**Comment by carlesjavierre** [comment]
Hello @PREngineer,

I've personally been using [GeoIP2](https://github.com/leev/ngx_http_geoip2_module) and it works flawlessly. Documentations is kinda vague but it's not really complicated. 

And yes, it is compatible, since what you're doing is telling VTS to add a new filter with other params, therefore you can add a filter of the country variable that has just been set up by that request. It'll result like this:

![image](https://user-images.githubusercontent.com/12613547/55812770-dfcbca80-5aeb-11e9-86ba-d96b111a0b6b.png)


Even LAT/LANG/CITY/POSTAL can be accomplished. You can do something like this on the http block:
```
    geoip2 /opt/geoip/GeoLite2-Country.mmdb {
        auto_reload 5m;
        $geoip2_metadata_country_build metadata build_epoch;
        $geoip2_data_country_code default=ES source=$remote_addr country iso_code;
        $geoip2_data_country_name country names es;
    }

    geoip2 /opt/geoip/GeoLite2-City.mmdb {
        $geoip2_data_city_name default=Madrid city names en;
        $geoip2_data_latitude location latitude;
        $geoip2_data_longitude location longitude;
        $geoip2_data_postalcode postal code;
    }

    vhost_traffic_status_dump /var/log/nginx/vts.db 60; # Backup Time
    vhost_traffic_status_zone;
    vhost_traffic_status_filter_by_set_key $geoip2_data_country_code country::*;
    vhost_traffic_status_filter_by_set_key $geoip2_data_city_name city::*;
    vhost_traffic_status_filter_by_set_key "$geoip2_data_latitude,$geoip2_data_longitude" latlong::*;
    vhost_traffic_status_filter_by_set_key $geoip2_data_longitude longitude::*;
    vhost_traffic_status_filter_by_set_key $geoip2_data_latitude latitude::*;
    vhost_traffic_status_filter_by_set_key $geoip2_data_postalcode postal::*;

``` 

Remember that you can just tell nginx to do that for every vhost, passing the server_name variable so you are able to do filters afterwards: 
```
vhost_traffic_status_filter_by_set_key $some_filter::$server_name
```

Hope that answered your questions

**Comment by PREngineer** [comment]
So, I will need to add an additional module.  Thanks.
