### ISSUE TITLE
Could not rmdir 'vext_cache': No such file or directory

### ISSUE THREAD

**Issue by iammeken** [vozlt/nginx-module-vts#254]
varnishd  -C -f /etc/varnish/default.vcl always gives this error, but vcl is ok and varnish runs ok.

varnish 7.2.1
ubuntu 22.04

**Comment by u5surf** [comment]
@iammeken Hi, Thanks reporting.
First of all, this repo is the module of nginx, not varnish. Thus it seems that your issue is not related to this repository issue. 
Can you tell us if your issue has any clue which can be related by nginx and this module? 
E.g Your system backend, proxy or load balancer is used nginx and this modules.
