### ISSUE TITLE
vts with upstream use zone parameter

### ISSUE THREAD

**Issue by saga1015** [vozlt/nginx-module-vts#55]
when upstream use "zone  xxx  size“，vts status page can not  output upstreams
only output ::nogroups

**Comment by saga1015** [comment]
![_2016-09-19t06-19-27 098z](https://cloud.githubusercontent.com/assets/14873189/18623840/5614ac04-7e74-11e6-9433-76fbc1351b71.png)

**Comment by vozlt** [comment]
Hi, I have some questions to confirm the situation.

1. The above, Is there all servers(172.16.5.*) belong in `exchange` group?
In other words, since nginx started the all servers in `::nogroups` belonged in `exchange` group?
2. Do you use any modules with `zone` directive?
3. How can I make the situation(simple nginx.conf)?

**Comment by saga1015** [comment]
@vozlt 172.16.5.* isn't belong in upstream "exchange", the “exchange" is not use "zone" parameter。
I use nginx-module-vts and ngx_dynamic_upstream.  ngx_dynamic_upstream use "zone" directive。

**Comment by saga1015** [comment]
my misstake ,haha ,now vts work fine

**Comment by Pereiro** [comment]
Hi, i have exactly the same problem. We use dynamic upstream module with vts module and use zone directives for all upstreams as it is necessary for dynamic_upstream module. And some of upstreams are in  ::nogroups section.

What was the reason of problem in your case?
