### ISSUE TITLE
[Question] Multiple nginx servers

### ISSUE THREAD

**Issue by MrMMorris** [vozlt/nginx-module-vts#69]
Hi!

Thanks for the awesome module!

I was wondering if it's possible and if so, how to set this up, if I have more than one nginx server?

Currently my setup looks like this:

```
              ELB
             /   \
           /       \
         /           \
      nginx LB     nginx LB
  /\     /\     /\     /\     /\
 /  \   /  \   /  \   /  \   /  \
   <-----Backend Servers----->
```

Is this possible? would I have to put another nginx server in front of the ones I currently have? or would I just have to find a way to combine the metrics for each server in Grafana?

Thanks!

**Comment by vozlt** [comment]
Hi, The feature to cluster is not currently implemented in `nginx-module-vts`.
I think that you'd better finding a new tool for merging JSON rather than putting another nginx server.
Or, I have never used Grafana, but it need the way you said "find a way to combine the metrics for each server in Grafana". Thanks.

There were similar issues.
https://github.com/vozlt/nginx-module-vts/issues/50
https://github.com/vozlt/nginx-module-vts/issues/39

**Comment by MrMMorris** [comment]
alright, thanks so much for your continued work!
